# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8619fe4af43d4e6e9a6ed0c10324e8323d62e4dc65189654d8e12dc2060ac6efab3ac8eeceeaa6c00d22db115b2dc7ecfb82b8876081b814e55a688ec1e343df

test:
  secret_key_base: 45bf85629d460023996dcc15309d2b1174c3b62267a40b8fb3e15fc4ce6b889d54fd8bbaffba1856de44142586cff7797b5367611bad474d979328db1efc0bce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
